version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    environment:
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
    volumes:
      - ./backend/app:/code/app
    ports:
      - "8080:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
