services:
  backend:
    build: 
      context: .
      dockerfile: backend/backend.dockerfile
    environment:
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
    volumes:
      - ./backend/app:/code/app
    ports:
      - "8080:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
      args:
        MAPBOX_TOKEN: ${MAPBOX_TOKEN}
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    volumes:
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
