version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    environment:
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
    volumes:
      - ./backend/app:/code/app
    ports:
      - "8080:80"
    networks:
      - app-network

  celery:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    command: celery -A app.app.celery_app.app worker --loglevel=info
    environment:
      - C_FORCE_ROOT=true
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
      args:
        MAPBOX_TOKEN: ${MAPBOX_TOKEN}
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    volumes:
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
