name: Deploy to DigitalOcean

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_PATH: /var/www/sermadrid

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH key to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    - name: Copy files to server
      run: |
        scp -r ./* ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }}:${{ env.APP_PATH }}

    - name: SSH and Deploy
      run: |
        ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'ENDSSH'
        cd ${{ env.APP_PATH }}
        docker-compose down
        docker-compose up -d --build
        ENDSSH