name: Deploy infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DO_SPACE_NAME: '${{ vars.DO_SPACE_NAME }}'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install DigitalOcean CLI
      run: |
        curl -sL https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar -xzv
        sudo mv doctl /usr/local/bin

    - name: Check and Create DigitalOcean Space
      run: |
        # Authenticate with DigitalOcean
        doctl auth init -t $DO_TOKEN

        # Check if the Space exists
        if ! doctl spaces bucket get $DO_SPACE_NAME; then
          # Create the Space if it doesn't exist
          doctl spaces bucket create $DO_SPACE_NAME
        fi
      env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        DO_SPACE_NAME: $DO_SPACE_NAME

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./infrastructure

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./infrastructure
      env:
        TF_VAR_do_space_name: $DO_SPACE_NAME
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        TF_VAR_ssh_fingerprint: ${{ secrets.SSH_FINGERPRINT }}
        TF_VAR_do_spaces_access_key: ${{ secrets.DO_SPACES_ACCESS_KEY }}
        TF_VAR_do_spaces_secret_key: ${{ secrets.DO_SPACES_SECRET_KEY }}
